services:
  frontend:
    image: like-her-frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8080"  # Map host port 8501 to container port 8080 where Streamlit is running
    volumes:
      - ./app/frontend:/app
      - ./data:/data
    environment:
      - API_URL=http://api:8080  # Updated to match the actual API port
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - backend_net

  api:
    image: like-her-api
    build:
      context: ./app/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./app/api:/app
      - ./data:/data
    environment:
      - MODEL_PATH=/data/models
      - PORT=8080  # The API is using port 8080
      - ENVIRONMENT=local
      - PROJECT_ID=local-dev
      - LOCATION=us-central1
      - AGENT_ID=local-dev-agent
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    restart: unless-stopped
    networks:
      - backend_net

  scheduler:
    image: like-her-scheduler
    build:
      context: ./app/scheduler
      dockerfile: Dockerfile
    volumes:
      - ./app/scheduler:/app
      - ./data:/data
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - backend_net

  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge