name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate to Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Set up Cloud SDK
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Enable necessary APIs
    - name: Enable APIs
      run: |
        gcloud services enable artifactregistry.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud services enable bigquery.googleapis.com
        gcloud services enable cloudscheduler.googleapis.com
        gcloud services enable secretmanager.googleapis.com

    # Configure Docker for GCR
    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io --quiet
        
    # Building and pushing API container
    - name: Build API container
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-api:latest ./app/api
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-api:latest

    # Building and pushing Frontend container
    - name: Build Frontend container
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-frontend:latest ./app/frontend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-frontend:latest

    # Building and pushing Scheduler container
    - name: Build Scheduler container
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-scheduler:latest ./app/scheduler
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-scheduler:latest

    # Set up Terraform with explicit Terraform Cloud token handling
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Create Terraform credentials file explicitly
    - name: Setup Terraform Credentials
      run: |
        cat > ~/.terraformrc << EOF
        credentials "app.terraform.io" {
          token = "${{ secrets.TF_API_TOKEN }}"
        }
        EOF
        chmod 0600 ~/.terraformrc

    # Initialize Terraform and handle resource state
    - name: Terraform Init and State Setup
      run: |
        cd infrastructure/terraform
        terraform init
        
        # Try to import Secret Manager secret if it exists
        terraform import google_secret_manager_secret.gemini_api_key projects/${{ secrets.GCP_PROJECT_ID }}/secrets/gemini-api-key || echo "Secret doesn't exist yet, will be created"
        
        # We'll let Terraform create BigQuery resources from scratch
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    # Apply Terraform with project_id, Gemini API key, AI Builder agent ID, and Google credentials
    - name: Terraform Apply
      run: |
        cd infrastructure/terraform
        terraform apply -auto-approve \
          -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var "gemini_api_key=${{ secrets.GEMINI_API_KEY }}" \
          -var "agent_id=${{ secrets.AGENT_ID }}" \
          -var "google_credentials=${{ secrets.GCP_SA_KEY }}"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    # Deploying to Cloud Run
    - name: Deploy API to Cloud Run
      run: |
        gcloud run deploy like-her-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-api:latest \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --service-account=admin-for-like-her@for-like-her.iam.gserviceaccount.com

    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy like-her-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/like-her-frontend:latest \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --service-account=admin-for-like-her@for-like-her.iam.gserviceaccount.com \
          --set-env-vars="API_URL=$(gcloud run services describe like-her-api --platform managed --region asia-northeast1 --format='value(status.url)')"