name: Setup Cloud Resources

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'  # Trigger only when infra code changes

jobs:
  setup-resources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Setup Terraform Cloud Token
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json << EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_API_TOKEN }}"
            }
          }
        }
        EOF
        chmod 0600 ~/.terraform.d/credentials.tfrc.json

    - name: Terraform Init and Apply
      run: |
        cd infrastructure/terraform
        terraform init
        terraform apply -auto-approve